// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogurodaoadocajgigytd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ndXJvZGFvYWRvY2FqZ2lneXRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDQxODUsImV4cCI6MjA2ODIyMDE4NX0.dMWh2bPWM1OvwI1GogaE__IKP76dSQUCawDcdc1HGis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});